[project]
name = "geometry"
version = "0.0.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.0.0"
description = "Two-dimensional geometry primitives for Encore applications"
readme = "README.md"
licence = "MIT"
dependencies = []
