[project]
name = "colorterm"
version = "0.0.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.0.0"
description = "ANSI color and style output helpers for Encore"
readme = "README.md"
licence = "MIT"
dependencies = []
