[project]
name = "platform"
version = "0.1.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.1.5, <0.3.0"
description = "Internal target-specific runtime and system bindings for Encore"
licence = "MIT"
dependencies = ["sys@core"]
