[project]
name = "lsp"
version = "0.0.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.0.0"
description = "Encore language server implemented in Encore"
readme = "README.md"
licence = "MIT"
dependencies = [
    "path@../../encore",
    "path@../packages/json",
    "path@../packages/std"
]
