[project]
name = "rich"
version = "0.0.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.0.0"
description = "Console rendering helpers inspired by Rich"
readme = "README.md"
licence = "MIT"
dependencies = [
    "path@../std",
    "path@../colorterm",
    "path@../json",
    "path@../log",
]
