[project]
name = "linalg"
version = "0.0.0"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.0.0"
description = "Vectors, matrices and transforms for Encore"
readme = "README.md"
licence = "MIT"
dependencies = ["index@std@0.0.0"]
