[project]
name = "json"
version = "1.0.1"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.1.5, <0.2.0"
description = "JSON parser and formatter for Encore"
readme = "README.md"
licence = "MIT"
dependencies = ["index@std@1.0.1"]
