[project]
name = "json"
version = "1.0.1"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.1.5, <0.3.0"
description = "JSON parser and formatter for Encore"
readme = "README.md"
licence = "MIT"
dependencies = ["path@../std"]
