[project]
name = "ehir_llvm_backend"
version = "0.0.1"
repository = "https://github.com/encore-ecosystem/encore-index"
encore = ">=0.1.4, <0.3.0"
description = "eHIR -> LLVM lowering backend"
readme = "README.md"
licence = "MIT"
dependencies = [
    "path@../std",
    "path@../ehir",
    "path@../llvm",
]
